apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryppb3911.azurecr.io/tripinsights/poi:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
